mysql:
  driver-class-name: "com.mysql.cj.jdbc.Driver"
  url: jdbc:mysql://133.186.244.96:3306/nhn_academy_21
  username: "nhn_academy_21"
  password: "*L]RAMG*8NYJnCKK"

discovery:
  id: admin
  password: admin
  ip: localhost

ioteatime:
  user:
    userDetailUri:
      http://localhost:8080/user