server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      force: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${discovery.id}:${discovery.password}@${discovery.ip}:8761/eureka

spring:
  application:
    name: api-service
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null

ioteatime:
  user:
    userDetailUri:
      http://localhost:8080/user

springdoc:
  swagger-ui:
    enabled: true
    version: "v0.1.0"

  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  model-and-view-allowed: true
