server:
  port: 0
  servlet:
    encoding:
      charset: UTF-8
      force: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${discovery.id}:${discovery.password}@${discovery.ip}:8761/eureka

spring:
  application:
    name: api-service
  profiles:
    active: prod

ioteatime:
  user:
    userDetailUri:
      http://localhost:8080/user
