server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${discovery.id}:${discovery.password}@${discovery.ip}:8761/eureka

spring:
  application:
    name: api-service
  profiles:
    active: prod
  jackson:
    default-property-inclusion: non_null

ioteatime:
  user:
    userDetailUri:
      http://localhost:8080/user
