server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      force: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${discovery.id}:${discovery.password}@${discovery.ip}:8761/eureka

spring:
  application:
    name: api-service
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  influx:
    url: http://127.0.0.1:8086/
    bucket: test
    org: test
    token: test

springdoc:
  packages-to-scan: live.ioteatime.apiservice
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /service
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /service/v3/api-docs
    groups:
      enabled: true
  cache:
    disabled: true