POST localhost:8090/outlier
Content-Type: application/json

{
  "place": "office",
  "type": "ac",
  "time": 19721121,
  "outlierValue": 12345,
  "flag": 0,
  "organizationId": 1
}

###
POST localhost:8090/outlier
Content-Type: application/json

{
  "place": "class_A",
  "type": "ac",
  "time": 11211972,
  "outlierValue": 54321,
  "flag": 0,
  "organizationId": 1
}

###
GET localhost:8090/outlier
Content-Type: application/json

###
PUT localhost:8090/outlier?id=1&flag=1
Content-Type: application/json