POST localhost:8090/outlier
Content-Type: application/json

{
  "outlier_id": 1,
  "place": "office",
  "type": "ac",
  "outlier_value": 12345,
  "flag": 0
}

###
POST localhost:8090/outlier
Content-Type: application/json

{
  "outlier_id": 0,
  "place": "class_A",
  "type": "ac",
  "outlier_value": 4321,
  "flag": 0
}

###
GET localhost:8090/outlier
Content-Type: application/json

###
PUT localhost:8090/outlier?id=2&flag=1
Content-Type: application/json