### 토픽 등록
POST http://localhost:8090/sensors/3/topics
X-USER-ID: admin
Content-Type: application/json

{
  "topic": "#",
  "description": "전체 조회"
}

### 토픽 리스트 조회
GET localhost:8090/sensors/3/topics
X-USER-ID: admin

### 토픽 단일 조회
GET localhost:8090/sensors/3/topics/20
X-USER-ID: admin

### 토픽 수정
PUT localhost:8090/sensors/3/topics/20/update
X-USER-ID: admin
Content-Type: application/json

{
  "topic": "topic/#",
  "description": "전체 조회 였었음"
}

### 토픽 삭제
DELETE localhost:8090/sensors/3/topics/20
X-USER-ID: admin